### PR TITLE
Use execa instead of child_process

### PR DESCRIPTION
**Pull request by rogermparent**
This PR changes the way link check invokes git by using a library called `execa` over `child_process.exec`, the former wrapping the latter with lots of quality of life improvements like a Promise-based API, enhanced Windows support, and most importantly a vastly increased buffer limit on stored output.

This should fix the issue where the checker fails when PR diffs are massive. There are other optimizations we can do as well (only diffing relevant files comes to mind) but this solution should suffice even without those.

### CODE REVIEW

**Review by julieg18 — COMMENTED** [review]
Code wise it looks good but when I tried to run the `cli.js` locally, I got an error. Are you able to run `yarn build` and `yarn dist/cli.js`? 

When I tried, I got a weird string of code then: 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/juliegalvan/Desktop/workspace/link-check/node_modules/execa/index.js from /Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js not supported.
Instead change the require of index.js in /Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.513 (/Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js:2:126)
    at t (/Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js:2:501)
    at /Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js:2:838
    at /Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js:2:27091
    at Object.<anonymous> (/Users/juliegalvan/Desktop/workspace/link-check/dist/cli.js:2:27095) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by rogermparent** [comment]
Weird! I was able to run `yarn build`, and run the package through `yarn link` on dvc.org, but maybe I got something tangled up in my system and that actually uses the old one. Thanks for the catch!

**Comment by rogermparent** [comment]
I was able to replicate that, I can definitely fix it but just need to find the best way- whether through webpack or `import()`.

**Comment by rogermparent** [comment]
The initial draft of the PR was rushed dog water, but after a package update, some API fixes, and some proper testing, things actually work.

**Review by shcheklein — APPROVED** [review]

**Review by yathomasi — COMMENTED** [review]
When I run `yarn build` on my machine, it generates other files with the `270` prefix. 
Beside that `cli.js` seems to be working fine on my test.
Screen Shot 2022-06-21 at 15 02 19

**Comment by rogermparent** [comment]
Good catch, I looked into it and found that an update to `node_fetch` added a `MultipartParser` class which is imported dynamically, so Webpack splits it into its own chunk by default. I'm sure some settings could force it all into one file, but it's probably best not to fight it.

**Pull request merged**
